export const FEISHU_LEADS_FIELDS = {
  reportId: "报告编号",
  createdAt: "提交时间",
  wechat: "微信号",
  email: "邮箱",
  currentEducation: "当前学历",
  targetDegree: "目标学历",
  targetCountry: "目标国家",
  targetMajor: "目标专业",
  intakeTime: "入学时间",
  schoolBackground: "学校背景",
  gpa: "GPA/均分",
  languageScore: "语言成绩",
  experiences: "经历摘要",
  budget: "家庭预算",
  scholarshipPreference: "奖学金偏好",
  acceptsNonPopular: "是否接受非热门国家",
  needsConsulting: "是否需要人工辅导",
  matchLevel: "匹配等级",
  matchScore: "匹配分数",
  leadQuality: "线索等级",
  reportStatus: "报告状态",
  followupStatus: "跟进状态",
  risks: "风险提示",
  nextSteps: "下一步建议",
  consultantNotes: "顾问备注",
} as const;

export const FEISHU_SCHOLARSHIP_FIELDS = {
  reportId: "报告编号",
  name: "奖学金名称",
  country: "国家",
  institution: "学校/机构",
  degreeLevel: "适合学历",
  scholarshipType: "奖学金类型",
  amount: "金额",
  deadline: "截止日期",
  officialUrl: "官网链接",
  sourceType: "来源类型",
  sourceReliability: "来源可靠性",
  aiConfidence: "AI置信度",
  matchReason: "匹配理由",
  risks: "风险提示",
  requiresHumanReview: "是否建议人工复核",
  advisorDecision: "顾问判断",
  advisorPriority: "顾问优先级",
  advisorNote: "顾问备注",
} as const;

export const FEISHU_AI_RUN_FIELDS = {
  runId: "运行编号",
  reportId: "报告编号",
  createdAt: "运行时间",
  runType: "运行类型",
  modelFast: "快速模型",
  modelStrong: "强模型",
  exaSearchCount: "Exa查询次数",
  processedUrlCount: "处理URL数",
  success: "是否成功",
  errorMessage: "错误信息",
} as const;
