import type { Scholarship } from "@/src/types";

const lastVerifiedAt = "2026-04-30";

export const mockScholarships: Scholarship[] = [
  {
    id: "uk-great-scholarship",
    name: "GREAT Scholarships 国际学生奖学金",
    country: "英国",
    institution: "英国高校与 British Council 合作项目",
    degreeLevel: ["硕士"],
    scholarshipType: "学费减免",
    amount: "通常为 £10,000 起，具体以院校官网为准",
    deadline: "待确认：不同院校截止日期不同",
    officialUrl: "https://study-uk.britishcouncil.org/scholarships-funding/great-scholarships",
    sourceType: "government",
    sourceReliability: "high",
    aiConfidence: 88,
    matchReason: "适合计划申请英国硕士、希望获得学费减免且需要官方项目背书的学生。",
    risks: "名额按院校和专业分配，截止日期差异较大，必须逐个院校官网核验。",
    requiresHumanReview: true,
    lastVerifiedAt,
  },
  {
    id: "erasmus-mundus-joint-masters",
    name: "Erasmus Mundus Joint Masters Scholarship",
    country: "欧洲多国",
    institution: "European Commission / 联合硕士项目联盟",
    degreeLevel: ["硕士"],
    scholarshipType: "全奖",
    amount: "通常覆盖学费、旅行补贴和生活津贴，具体以项目官网为准",
    deadline: "待确认：项目制滚动更新",
    officialUrl: "https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/erasmus-mundus-joint-masters",
    sourceType: "international_org",
    sourceReliability: "high",
    aiConfidence: 84,
    matchReason: "适合接受跨国联合培养、愿意扩大欧洲项目池且希望争取高覆盖奖学金的学生。",
    risks: "项目方向分散，申请材料和语言要求差异明显，需要人工筛选匹配专业。",
    requiresHumanReview: true,
    lastVerifiedAt,
  },
  {
    id: "daad-development-scholarship",
    name: "DAAD Development-Related Postgraduate Scholarship",
    country: "德国",
    institution: "DAAD 德意志学术交流中心",
    degreeLevel: ["硕士", "博士"],
    scholarshipType: "生活补助",
    amount: "月度生活津贴、保险及部分旅行补贴，具体金额以 DAAD 官网为准",
    deadline: "待确认：按项目和院校分别设置",
    officialUrl: "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
    sourceType: "government",
    sourceReliability: "high",
    aiConfidence: 80,
    matchReason: "适合有明确学术或发展方向、预算有限且可接受德国或欧洲非热门项目的学生。",
    risks: "部分项目要求工作经验或发展相关背景，需要核验具体项目资格。",
    requiresHumanReview: true,
    lastVerifiedAt,
  },
  {
    id: "australia-awards",
    name: "Australia Awards Scholarships",
    country: "澳大利亚",
    institution: "Australian Government",
    degreeLevel: ["本科", "硕士", "博士"],
    scholarshipType: "全奖",
    amount: "通常覆盖学费、生活津贴、保险和旅行支持，资格以官网为准",
    deadline: "待确认：不同国家/地区申请轮次不同",
    officialUrl: "https://www.dfat.gov.au/people-to-people/australia-awards",
    sourceType: "government",
    sourceReliability: "high",
    aiConfidence: 76,
    matchReason: "适合希望争取政府类高覆盖资助，并能接受较强资格筛选的申请人。",
    risks: "国家/地区资格限制较强，中国学生是否适用需人工核验。",
    requiresHumanReview: true,
    lastVerifiedAt,
  },
  {
    id: "university-merit-awards",
    name: "University Merit-based International Awards",
    country: "多国方向",
    institution: "目标院校学院/招生办公室",
    degreeLevel: ["本科", "硕士"],
    scholarshipType: "半奖",
    amount: "学费 10%–50% 减免较常见，以具体院校官网为准",
    deadline: "待确认：通常与申请轮次绑定",
    officialUrl: "https://example.com/official-placeholder",
    sourceType: "university",
    sourceReliability: "medium",
    aiConfidence: 72,
    matchReason: "适合 GPA、语言和经历较均衡，希望在目标院校中争取自动评估或学院奖的学生。",
    risks: "当前为类型化 mock 机会，需要顾问按目标院校逐项替换为真实官网链接。",
    requiresHumanReview: true,
    lastVerifiedAt,
  },
];
