import type { Scholarship } from "@/types";

export const mockScholarships: Scholarship[] = [
  {
    id: "eu-erasmus-mundus",
    name: "Erasmus Mundus Joint Masters Scholarship",
    country: "欧盟/多国联合",
    degreeLevels: ["硕士"],
    type: "全奖",
    difficulty: "较高",
    suitableMajors: ["商科", "工程", "数据科学", "社会科学", "环境", "教育"],
    matchReason: "适合有跨国学习意愿、英语能力较好且背景综合竞争力强的硕士申请人。",
    risk: "项目选择和文书要求较高，申请批次与项目官网要求差异较大，需要逐项核验。",
    officialUrl: "https://example.com/erasmus-mundus",
  },
  {
    id: "uk-great-scholarship",
    name: "GREAT Scholarships 英国专项奖学金",
    country: "英国",
    degreeLevels: ["硕士"],
    type: "学费减免",
    difficulty: "中等",
    suitableMajors: ["商科", "传媒", "教育", "工程", "法律"],
    matchReason: "适合目标英国授课型硕士、希望降低学费压力且有明确职业规划的申请人。",
    risk: "名额有限，覆盖院校和专业每年变化，通常需要先拿到录取或同步申请。",
    officialUrl: "https://example.com/great-scholarship",
  },
  {
    id: "aus-destination",
    name: "Australia Destination Scholarship",
    country: "澳大利亚",
    degreeLevels: ["本科", "硕士", "博士"],
    type: "生活补助",
    difficulty: "中等",
    suitableMajors: ["护理", "工程", "农业", "教育", "IT"],
    matchReason: "适合能接受非一线城市或区域院校、希望兼顾留学预算与移民规划的学生。",
    risk: "区域院校选择会影响专业排名和就业路径，需要结合长期目标判断。",
    officialUrl: "https://example.com/australia-destination",
  },
  {
    id: "canada-grad-funding",
    name: "Canadian Graduate Research Funding",
    country: "加拿大",
    degreeLevels: ["硕士", "博士"],
    type: "混合资助",
    difficulty: "较高",
    suitableMajors: ["理工科", "生命科学", "计算机", "社会科学"],
    matchReason: "适合具备科研经历、论文或强推荐信的研究型硕博申请人。",
    risk: "高度依赖导师名额和研究方向匹配，需要提前套磁并准备研究计划。",
    officialUrl: "https://example.com/canada-grad-funding",
  },
  {
    id: "asia-university-merit",
    name: "Asian University Merit Scholarship",
    country: "新加坡/中国香港/马来西亚",
    degreeLevels: ["本科", "硕士"],
    type: "半奖",
    difficulty: "中等",
    suitableMajors: ["商科", "计算机", "工程", "传媒", "公共政策"],
    matchReason: "适合希望离家较近、预算较敏感，同时具备较好成绩和英语基础的申请人。",
    risk: "热门地区竞争激烈，奖学金通常与录取质量、面试表现和申请轮次强相关。",
    officialUrl: "https://example.com/asia-merit",
  },
  {
    id: "nonpopular-tuition-waiver",
    name: "非热门国家英文项目学费减免奖学金",
    country: "欧洲非热门国家/亚洲新兴目的地",
    degreeLevels: ["本科", "硕士", "博士", "交换/访学"],
    type: "学费减免",
    difficulty: "较低",
    suitableMajors: ["商科", "工程", "医学相关", "艺术", "人文社科"],
    matchReason: "适合预算有限、愿意扩大国家和院校选择范围，以奖学金和性价比为优先级的学生。",
    risk: "院校知名度、当地语言环境和毕业后路径需要额外评估。",
    officialUrl: "https://example.com/tuition-waiver",
  },
];
